const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.AJAX,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.RotateTowardPosition
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Teclado: 0},
	{"8Direções": 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{protagonist: 0},
	{Health: 0},
	{Projétil: 0},
	{zombie: 0},
	{DestruirForaDoLayout: 0},
	{bullet: 0},
	{Esmaecer: 0},
	{flame: 0},
	{blood: 0},
	{Score: 0},
	{RankingDeJogadores: 0},
	{NomeJogador: 0},
	{Enviar: 0},
	{AJAX: 0},
	{Sprite: 0},
	{fundo2: 0},
	{fundo3: 0},
	{Pontos: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	protagonist: class extends self.ISpriteInstance {},
	zombie: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	flame: class extends self.ISpriteInstance {},
	blood: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	RankingDeJogadores: class extends self.ITextInstance {},
	NomeJogador: class extends self.ITextInputInstance {},
	Enviar: class extends self.IButtonInstance {},
	AJAX: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	fundo2: class extends self.ISpriteInstance {},
	fundo3: class extends self.ISpriteInstance {}
}